# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lukasz/workspace/black_jack

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lukasz/workspace/black_jack

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukasz/workspace/black_jack/CMakeFiles /home/lukasz/workspace/black_jack/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lukasz/workspace/black_jack/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named black_jack

# Build rule for target.
black_jack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 black_jack
.PHONY : black_jack

# fast build rule for target.
black_jack/fast:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/build
.PHONY : black_jack/fast

src/BasicStrategy.o: src/BasicStrategy.cpp.o
.PHONY : src/BasicStrategy.o

# target to build an object file
src/BasicStrategy.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/BasicStrategy.cpp.o
.PHONY : src/BasicStrategy.cpp.o

src/BasicStrategy.i: src/BasicStrategy.cpp.i
.PHONY : src/BasicStrategy.i

# target to preprocess a source file
src/BasicStrategy.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/BasicStrategy.cpp.i
.PHONY : src/BasicStrategy.cpp.i

src/BasicStrategy.s: src/BasicStrategy.cpp.s
.PHONY : src/BasicStrategy.s

# target to generate assembly for a file
src/BasicStrategy.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/BasicStrategy.cpp.s
.PHONY : src/BasicStrategy.cpp.s

src/Box.o: src/Box.cpp.o
.PHONY : src/Box.o

# target to build an object file
src/Box.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Box.cpp.o
.PHONY : src/Box.cpp.o

src/Box.i: src/Box.cpp.i
.PHONY : src/Box.i

# target to preprocess a source file
src/Box.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Box.cpp.i
.PHONY : src/Box.cpp.i

src/Box.s: src/Box.cpp.s
.PHONY : src/Box.s

# target to generate assembly for a file
src/Box.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Box.cpp.s
.PHONY : src/Box.cpp.s

src/Card.o: src/Card.cpp.o
.PHONY : src/Card.o

# target to build an object file
src/Card.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Card.cpp.o
.PHONY : src/Card.cpp.o

src/Card.i: src/Card.cpp.i
.PHONY : src/Card.i

# target to preprocess a source file
src/Card.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Card.cpp.i
.PHONY : src/Card.cpp.i

src/Card.s: src/Card.cpp.s
.PHONY : src/Card.s

# target to generate assembly for a file
src/Card.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Card.cpp.s
.PHONY : src/Card.cpp.s

src/Dealer.o: src/Dealer.cpp.o
.PHONY : src/Dealer.o

# target to build an object file
src/Dealer.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Dealer.cpp.o
.PHONY : src/Dealer.cpp.o

src/Dealer.i: src/Dealer.cpp.i
.PHONY : src/Dealer.i

# target to preprocess a source file
src/Dealer.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Dealer.cpp.i
.PHONY : src/Dealer.cpp.i

src/Dealer.s: src/Dealer.cpp.s
.PHONY : src/Dealer.s

# target to generate assembly for a file
src/Dealer.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Dealer.cpp.s
.PHONY : src/Dealer.cpp.s

src/Decision.o: src/Decision.cpp.o
.PHONY : src/Decision.o

# target to build an object file
src/Decision.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Decision.cpp.o
.PHONY : src/Decision.cpp.o

src/Decision.i: src/Decision.cpp.i
.PHONY : src/Decision.i

# target to preprocess a source file
src/Decision.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Decision.cpp.i
.PHONY : src/Decision.cpp.i

src/Decision.s: src/Decision.cpp.s
.PHONY : src/Decision.s

# target to generate assembly for a file
src/Decision.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Decision.cpp.s
.PHONY : src/Decision.cpp.s

src/Deck.o: src/Deck.cpp.o
.PHONY : src/Deck.o

# target to build an object file
src/Deck.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Deck.cpp.o
.PHONY : src/Deck.cpp.o

src/Deck.i: src/Deck.cpp.i
.PHONY : src/Deck.i

# target to preprocess a source file
src/Deck.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Deck.cpp.i
.PHONY : src/Deck.cpp.i

src/Deck.s: src/Deck.cpp.s
.PHONY : src/Deck.s

# target to generate assembly for a file
src/Deck.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Deck.cpp.s
.PHONY : src/Deck.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Person.o: src/Person.cpp.o
.PHONY : src/Person.o

# target to build an object file
src/Person.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Person.cpp.o
.PHONY : src/Person.cpp.o

src/Person.i: src/Person.cpp.i
.PHONY : src/Person.i

# target to preprocess a source file
src/Person.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Person.cpp.i
.PHONY : src/Person.cpp.i

src/Person.s: src/Person.cpp.s
.PHONY : src/Person.s

# target to generate assembly for a file
src/Person.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Person.cpp.s
.PHONY : src/Person.cpp.s

src/Person_old.o: src/Person_old.cpp.o
.PHONY : src/Person_old.o

# target to build an object file
src/Person_old.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Person_old.cpp.o
.PHONY : src/Person_old.cpp.o

src/Person_old.i: src/Person_old.cpp.i
.PHONY : src/Person_old.i

# target to preprocess a source file
src/Person_old.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Person_old.cpp.i
.PHONY : src/Person_old.cpp.i

src/Person_old.s: src/Person_old.cpp.s
.PHONY : src/Person_old.s

# target to generate assembly for a file
src/Person_old.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Person_old.cpp.s
.PHONY : src/Person_old.cpp.s

src/Player.o: src/Player.cpp.o
.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i
.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s
.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Strategy.o: src/Strategy.cpp.o
.PHONY : src/Strategy.o

# target to build an object file
src/Strategy.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Strategy.cpp.o
.PHONY : src/Strategy.cpp.o

src/Strategy.i: src/Strategy.cpp.i
.PHONY : src/Strategy.i

# target to preprocess a source file
src/Strategy.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Strategy.cpp.i
.PHONY : src/Strategy.cpp.i

src/Strategy.s: src/Strategy.cpp.s
.PHONY : src/Strategy.s

# target to generate assembly for a file
src/Strategy.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Strategy.cpp.s
.PHONY : src/Strategy.cpp.s

src/Take17.o: src/Take17.cpp.o
.PHONY : src/Take17.o

# target to build an object file
src/Take17.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Take17.cpp.o
.PHONY : src/Take17.cpp.o

src/Take17.i: src/Take17.cpp.i
.PHONY : src/Take17.i

# target to preprocess a source file
src/Take17.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Take17.cpp.i
.PHONY : src/Take17.cpp.i

src/Take17.s: src/Take17.cpp.s
.PHONY : src/Take17.s

# target to generate assembly for a file
src/Take17.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/Take17.cpp.s
.PHONY : src/Take17.cpp.s

src/basic_strategy.o: src/basic_strategy.cpp.o
.PHONY : src/basic_strategy.o

# target to build an object file
src/basic_strategy.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/basic_strategy.cpp.o
.PHONY : src/basic_strategy.cpp.o

src/basic_strategy.i: src/basic_strategy.cpp.i
.PHONY : src/basic_strategy.i

# target to preprocess a source file
src/basic_strategy.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/basic_strategy.cpp.i
.PHONY : src/basic_strategy.cpp.i

src/basic_strategy.s: src/basic_strategy.cpp.s
.PHONY : src/basic_strategy.s

# target to generate assembly for a file
src/basic_strategy.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/basic_strategy.cpp.s
.PHONY : src/basic_strategy.cpp.s

src/decision.o: src/decision.cpp.o
.PHONY : src/decision.o

# target to build an object file
src/decision.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/decision.cpp.o
.PHONY : src/decision.cpp.o

src/decision.i: src/decision.cpp.i
.PHONY : src/decision.i

# target to preprocess a source file
src/decision.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/decision.cpp.i
.PHONY : src/decision.cpp.i

src/decision.s: src/decision.cpp.s
.PHONY : src/decision.s

# target to generate assembly for a file
src/decision.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/decision.cpp.s
.PHONY : src/decision.cpp.s

src/decision_adv.o: src/decision_adv.cpp.o
.PHONY : src/decision_adv.o

# target to build an object file
src/decision_adv.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/decision_adv.cpp.o
.PHONY : src/decision_adv.cpp.o

src/decision_adv.i: src/decision_adv.cpp.i
.PHONY : src/decision_adv.i

# target to preprocess a source file
src/decision_adv.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/decision_adv.cpp.i
.PHONY : src/decision_adv.cpp.i

src/decision_adv.s: src/decision_adv.cpp.s
.PHONY : src/decision_adv.s

# target to generate assembly for a file
src/decision_adv.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/decision_adv.cpp.s
.PHONY : src/decision_adv.cpp.s

src/gambler.o: src/gambler.cpp.o
.PHONY : src/gambler.o

# target to build an object file
src/gambler.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/gambler.cpp.o
.PHONY : src/gambler.cpp.o

src/gambler.i: src/gambler.cpp.i
.PHONY : src/gambler.i

# target to preprocess a source file
src/gambler.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/gambler.cpp.i
.PHONY : src/gambler.cpp.i

src/gambler.s: src/gambler.cpp.s
.PHONY : src/gambler.s

# target to generate assembly for a file
src/gambler.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/gambler.cpp.s
.PHONY : src/gambler.cpp.s

src/game.o: src/game.cpp.o
.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/hi_low_i.o: src/hi_low_i.cpp.o
.PHONY : src/hi_low_i.o

# target to build an object file
src/hi_low_i.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/hi_low_i.cpp.o
.PHONY : src/hi_low_i.cpp.o

src/hi_low_i.i: src/hi_low_i.cpp.i
.PHONY : src/hi_low_i.i

# target to preprocess a source file
src/hi_low_i.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/hi_low_i.cpp.i
.PHONY : src/hi_low_i.cpp.i

src/hi_low_i.s: src/hi_low_i.cpp.s
.PHONY : src/hi_low_i.s

# target to generate assembly for a file
src/hi_low_i.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/hi_low_i.cpp.s
.PHONY : src/hi_low_i.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/player_test.o: src/player_test.cpp.o
.PHONY : src/player_test.o

# target to build an object file
src/player_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/player_test.cpp.o
.PHONY : src/player_test.cpp.o

src/player_test.i: src/player_test.cpp.i
.PHONY : src/player_test.i

# target to preprocess a source file
src/player_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/player_test.cpp.i
.PHONY : src/player_test.cpp.i

src/player_test.s: src/player_test.cpp.s
.PHONY : src/player_test.s

# target to generate assembly for a file
src/player_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/src/player_test.cpp.s
.PHONY : src/player_test.cpp.s

test/BasicStrategy_test.o: test/BasicStrategy_test.cpp.o
.PHONY : test/BasicStrategy_test.o

# target to build an object file
test/BasicStrategy_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/BasicStrategy_test.cpp.o
.PHONY : test/BasicStrategy_test.cpp.o

test/BasicStrategy_test.i: test/BasicStrategy_test.cpp.i
.PHONY : test/BasicStrategy_test.i

# target to preprocess a source file
test/BasicStrategy_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/BasicStrategy_test.cpp.i
.PHONY : test/BasicStrategy_test.cpp.i

test/BasicStrategy_test.s: test/BasicStrategy_test.cpp.s
.PHONY : test/BasicStrategy_test.s

# target to generate assembly for a file
test/BasicStrategy_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/BasicStrategy_test.cpp.s
.PHONY : test/BasicStrategy_test.cpp.s

test/Box_test.o: test/Box_test.cpp.o
.PHONY : test/Box_test.o

# target to build an object file
test/Box_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Box_test.cpp.o
.PHONY : test/Box_test.cpp.o

test/Box_test.i: test/Box_test.cpp.i
.PHONY : test/Box_test.i

# target to preprocess a source file
test/Box_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Box_test.cpp.i
.PHONY : test/Box_test.cpp.i

test/Box_test.s: test/Box_test.cpp.s
.PHONY : test/Box_test.s

# target to generate assembly for a file
test/Box_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Box_test.cpp.s
.PHONY : test/Box_test.cpp.s

test/Card_test.o: test/Card_test.cpp.o
.PHONY : test/Card_test.o

# target to build an object file
test/Card_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Card_test.cpp.o
.PHONY : test/Card_test.cpp.o

test/Card_test.i: test/Card_test.cpp.i
.PHONY : test/Card_test.i

# target to preprocess a source file
test/Card_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Card_test.cpp.i
.PHONY : test/Card_test.cpp.i

test/Card_test.s: test/Card_test.cpp.s
.PHONY : test/Card_test.s

# target to generate assembly for a file
test/Card_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Card_test.cpp.s
.PHONY : test/Card_test.cpp.s

test/Dealer_test.o: test/Dealer_test.cpp.o
.PHONY : test/Dealer_test.o

# target to build an object file
test/Dealer_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Dealer_test.cpp.o
.PHONY : test/Dealer_test.cpp.o

test/Dealer_test.i: test/Dealer_test.cpp.i
.PHONY : test/Dealer_test.i

# target to preprocess a source file
test/Dealer_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Dealer_test.cpp.i
.PHONY : test/Dealer_test.cpp.i

test/Dealer_test.s: test/Dealer_test.cpp.s
.PHONY : test/Dealer_test.s

# target to generate assembly for a file
test/Dealer_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Dealer_test.cpp.s
.PHONY : test/Dealer_test.cpp.s

test/Decision_test.o: test/Decision_test.cpp.o
.PHONY : test/Decision_test.o

# target to build an object file
test/Decision_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Decision_test.cpp.o
.PHONY : test/Decision_test.cpp.o

test/Decision_test.i: test/Decision_test.cpp.i
.PHONY : test/Decision_test.i

# target to preprocess a source file
test/Decision_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Decision_test.cpp.i
.PHONY : test/Decision_test.cpp.i

test/Decision_test.s: test/Decision_test.cpp.s
.PHONY : test/Decision_test.s

# target to generate assembly for a file
test/Decision_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Decision_test.cpp.s
.PHONY : test/Decision_test.cpp.s

test/Deck_test.o: test/Deck_test.cpp.o
.PHONY : test/Deck_test.o

# target to build an object file
test/Deck_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Deck_test.cpp.o
.PHONY : test/Deck_test.cpp.o

test/Deck_test.i: test/Deck_test.cpp.i
.PHONY : test/Deck_test.i

# target to preprocess a source file
test/Deck_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Deck_test.cpp.i
.PHONY : test/Deck_test.cpp.i

test/Deck_test.s: test/Deck_test.cpp.s
.PHONY : test/Deck_test.s

# target to generate assembly for a file
test/Deck_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Deck_test.cpp.s
.PHONY : test/Deck_test.cpp.s

test/Game_test.o: test/Game_test.cpp.o
.PHONY : test/Game_test.o

# target to build an object file
test/Game_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Game_test.cpp.o
.PHONY : test/Game_test.cpp.o

test/Game_test.i: test/Game_test.cpp.i
.PHONY : test/Game_test.i

# target to preprocess a source file
test/Game_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Game_test.cpp.i
.PHONY : test/Game_test.cpp.i

test/Game_test.s: test/Game_test.cpp.s
.PHONY : test/Game_test.s

# target to generate assembly for a file
test/Game_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Game_test.cpp.s
.PHONY : test/Game_test.cpp.s

test/Person_old_test.o: test/Person_old_test.cpp.o
.PHONY : test/Person_old_test.o

# target to build an object file
test/Person_old_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Person_old_test.cpp.o
.PHONY : test/Person_old_test.cpp.o

test/Person_old_test.i: test/Person_old_test.cpp.i
.PHONY : test/Person_old_test.i

# target to preprocess a source file
test/Person_old_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Person_old_test.cpp.i
.PHONY : test/Person_old_test.cpp.i

test/Person_old_test.s: test/Person_old_test.cpp.s
.PHONY : test/Person_old_test.s

# target to generate assembly for a file
test/Person_old_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Person_old_test.cpp.s
.PHONY : test/Person_old_test.cpp.s

test/Person_test.o: test/Person_test.cpp.o
.PHONY : test/Person_test.o

# target to build an object file
test/Person_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Person_test.cpp.o
.PHONY : test/Person_test.cpp.o

test/Person_test.i: test/Person_test.cpp.i
.PHONY : test/Person_test.i

# target to preprocess a source file
test/Person_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Person_test.cpp.i
.PHONY : test/Person_test.cpp.i

test/Person_test.s: test/Person_test.cpp.s
.PHONY : test/Person_test.s

# target to generate assembly for a file
test/Person_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Person_test.cpp.s
.PHONY : test/Person_test.cpp.s

test/Player_test.o: test/Player_test.cpp.o
.PHONY : test/Player_test.o

# target to build an object file
test/Player_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Player_test.cpp.o
.PHONY : test/Player_test.cpp.o

test/Player_test.i: test/Player_test.cpp.i
.PHONY : test/Player_test.i

# target to preprocess a source file
test/Player_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Player_test.cpp.i
.PHONY : test/Player_test.cpp.i

test/Player_test.s: test/Player_test.cpp.s
.PHONY : test/Player_test.s

# target to generate assembly for a file
test/Player_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Player_test.cpp.s
.PHONY : test/Player_test.cpp.s

test/Strategy_test.o: test/Strategy_test.cpp.o
.PHONY : test/Strategy_test.o

# target to build an object file
test/Strategy_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Strategy_test.cpp.o
.PHONY : test/Strategy_test.cpp.o

test/Strategy_test.i: test/Strategy_test.cpp.i
.PHONY : test/Strategy_test.i

# target to preprocess a source file
test/Strategy_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Strategy_test.cpp.i
.PHONY : test/Strategy_test.cpp.i

test/Strategy_test.s: test/Strategy_test.cpp.s
.PHONY : test/Strategy_test.s

# target to generate assembly for a file
test/Strategy_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Strategy_test.cpp.s
.PHONY : test/Strategy_test.cpp.s

test/Take17_test.o: test/Take17_test.cpp.o
.PHONY : test/Take17_test.o

# target to build an object file
test/Take17_test.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Take17_test.cpp.o
.PHONY : test/Take17_test.cpp.o

test/Take17_test.i: test/Take17_test.cpp.i
.PHONY : test/Take17_test.i

# target to preprocess a source file
test/Take17_test.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Take17_test.cpp.i
.PHONY : test/Take17_test.cpp.i

test/Take17_test.s: test/Take17_test.cpp.s
.PHONY : test/Take17_test.s

# target to generate assembly for a file
test/Take17_test.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/Take17_test.cpp.s
.PHONY : test/Take17_test.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/black_jack.dir/build.make CMakeFiles/black_jack.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... black_jack"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/BasicStrategy.o"
	@echo "... src/BasicStrategy.i"
	@echo "... src/BasicStrategy.s"
	@echo "... src/Box.o"
	@echo "... src/Box.i"
	@echo "... src/Box.s"
	@echo "... src/Card.o"
	@echo "... src/Card.i"
	@echo "... src/Card.s"
	@echo "... src/Dealer.o"
	@echo "... src/Dealer.i"
	@echo "... src/Dealer.s"
	@echo "... src/Decision.o"
	@echo "... src/Decision.i"
	@echo "... src/Decision.s"
	@echo "... src/Deck.o"
	@echo "... src/Deck.i"
	@echo "... src/Deck.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Person.o"
	@echo "... src/Person.i"
	@echo "... src/Person.s"
	@echo "... src/Person_old.o"
	@echo "... src/Person_old.i"
	@echo "... src/Person_old.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Strategy.o"
	@echo "... src/Strategy.i"
	@echo "... src/Strategy.s"
	@echo "... src/Take17.o"
	@echo "... src/Take17.i"
	@echo "... src/Take17.s"
	@echo "... src/basic_strategy.o"
	@echo "... src/basic_strategy.i"
	@echo "... src/basic_strategy.s"
	@echo "... src/decision.o"
	@echo "... src/decision.i"
	@echo "... src/decision.s"
	@echo "... src/decision_adv.o"
	@echo "... src/decision_adv.i"
	@echo "... src/decision_adv.s"
	@echo "... src/gambler.o"
	@echo "... src/gambler.i"
	@echo "... src/gambler.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/hi_low_i.o"
	@echo "... src/hi_low_i.i"
	@echo "... src/hi_low_i.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/player_test.o"
	@echo "... src/player_test.i"
	@echo "... src/player_test.s"
	@echo "... test/BasicStrategy_test.o"
	@echo "... test/BasicStrategy_test.i"
	@echo "... test/BasicStrategy_test.s"
	@echo "... test/Box_test.o"
	@echo "... test/Box_test.i"
	@echo "... test/Box_test.s"
	@echo "... test/Card_test.o"
	@echo "... test/Card_test.i"
	@echo "... test/Card_test.s"
	@echo "... test/Dealer_test.o"
	@echo "... test/Dealer_test.i"
	@echo "... test/Dealer_test.s"
	@echo "... test/Decision_test.o"
	@echo "... test/Decision_test.i"
	@echo "... test/Decision_test.s"
	@echo "... test/Deck_test.o"
	@echo "... test/Deck_test.i"
	@echo "... test/Deck_test.s"
	@echo "... test/Game_test.o"
	@echo "... test/Game_test.i"
	@echo "... test/Game_test.s"
	@echo "... test/Person_old_test.o"
	@echo "... test/Person_old_test.i"
	@echo "... test/Person_old_test.s"
	@echo "... test/Person_test.o"
	@echo "... test/Person_test.i"
	@echo "... test/Person_test.s"
	@echo "... test/Player_test.o"
	@echo "... test/Player_test.i"
	@echo "... test/Player_test.s"
	@echo "... test/Strategy_test.o"
	@echo "... test/Strategy_test.i"
	@echo "... test/Strategy_test.s"
	@echo "... test/Take17_test.o"
	@echo "... test/Take17_test.i"
	@echo "... test/Take17_test.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

